name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        docker: [ { dir: python, name: python-cross }, ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        echo "Building and pushing image for ${ matrix.docker.dir } with name ${ matrix.docker.name }"
        docker build -f ${ matrix.docker.dir }/Dockerfile -t ghcr.io/${{ github.repository }}/${ matrix.docker.name }:latest .
        docker push ghcr.io/${{ github.repository }}/${ matrix.docker.name }:latest
